export { GitApiClientProvider, useGitApiClient, useGitApiMutation, useGitApiQuery } from "./hooks/query.js";
export {
  applyGitStarOptimisticState,
  applyGitWatchOptimisticState,
  useGitArchive,
  useGitActivity,
  useGitBlame,
  useGitBlob,
  useGitBranches,
  useGitCommit,
  useGitCommits,
  useGitCreateFork,
  useGitCreateRelease,
  useGitDeleteRelease,
  useGitDiff,
  useGitForks,
  useGitLinguist,
  useGitOverview,
  useGitRelease,
  useGitReleases,
  useGitRepositorySummary,
  useGitSearch,
  useGitSocialState,
  useGitStarRepository,
  useGitSyncFork,
  useGitTag,
  useGitTags,
  useGitTree,
  useGitUnstarRepository,
  useGitUnwatchRepository,
  useGitUpdateRelease,
  useGitWatchRepository,
} from "./hooks/resources.js";

export type {
  GitApiClientProviderProps,
  GitApiMutationResult,
  GitApiQueryOptions,
  GitApiQueryResult,
  UseGitArchiveOptions,
  UseGitActivityOptions,
  UseGitBlameOptions,
  UseGitBlobOptions,
  UseGitCommitsOptions,
  UseGitDiffOptions,
  UseGitForksOptions,
  UseGitLinguistOptions,
  UseGitOverviewOptions,
  UseGitReleaseOptions,
  UseGitReleasesOptions,
  UseGitRepositorySummaryOptions,
  UseGitSearchOptions,
  UseGitSocialStateOptions,
  UseGitTagOptions,
  UseGitTagsOptions,
  UseGitTreeOptions,
} from "./hooks/types.js";
