export { GitApiClientError, createGitApiClient } from "./client.js";
export {
  GitApiClientProvider,
  useGitApiClient,
  useGitApiMutation,
  useGitApiQuery,
  applyGitStarOptimisticState,
  applyGitWatchOptimisticState,
  useGitArchive,
  useGitActivity,
  useGitBlame,
  useGitBlob,
  useGitBranches,
  useGitCommit,
  useGitCommits,
  useGitCreateFork,
  useGitCreateRelease,
  useGitDeleteRelease,
  useGitDiff,
  useGitForks,
  useGitLinguist,
  useGitOverview,
  useGitRelease,
  useGitReleases,
  useGitRepositorySummary,
  useGitSearch,
  useGitSocialState,
  useGitStarRepository,
  useGitSyncFork,
  useGitTag,
  useGitTags,
  useGitTree,
  useGitUnstarRepository,
  useGitUnwatchRepository,
  useGitUpdateRelease,
  useGitWatchRepository,
} from "./hooks.js";

export type {
  CreateGitApiClientOptions,
  GitApiEventStream,
  GitApiClient,
  GitApiClientFetch,
  GitApiClientHeaders,
  GitApiClientRequestOptions,
  GitApiFailureResponse,
  GitApiHeaderResolver,
  GitApiResponse,
  GitApiSuccessResponse,
  GitLinguistSocketDoneEvent,
  GitLinguistSocketErrorEvent,
  GitLinguistSocketEvent,
  GitLinguistSocketProgressEvent,
  GitLinguistSocketResultEvent,
} from "./client.js";
export type {
  GitApiClientProviderProps,
  GitApiMutationResult,
  GitApiQueryOptions,
  GitApiQueryResult,
  UseGitArchiveOptions,
  UseGitActivityOptions,
  UseGitBlameOptions,
  UseGitBlobOptions,
  UseGitCommitsOptions,
  UseGitDiffOptions,
  UseGitForksOptions,
  UseGitLinguistOptions,
  UseGitOverviewOptions,
  UseGitReleaseOptions,
  UseGitReleasesOptions,
  UseGitRepositorySummaryOptions,
  UseGitSearchOptions,
  UseGitSocialStateOptions,
  UseGitTagOptions,
  UseGitTagsOptions,
  UseGitTreeOptions,
} from "./hooks.js";
