export {
  DEFAULT_ACTOR_EMAIL,
  DEFAULT_ACTOR_NAME,
  DEFAULT_BRANCH,
  DEFAULT_COMMIT_MESSAGE,
  DEFAULT_MANAGED_EXCLUDE_HEADER,
  DEFAULT_MANAGED_EXCLUDE_PATTERNS,
} from "./constants.js";
export { RepositoryLockManager } from "./core/locks.js";
export { readRepositoryOperationState } from "./core/operation_state.js";
export { createGitHost } from "./core/create_git_host.js";
export { createGitApiHandler, parseGitApiRoute } from "./api/handler.js";
export { fetchRepository, pullRepository, pushRepository } from "./core/remote.js";
export { createGitHttpHandler, parseGitHttpRoute } from "./http/handler.js";
export {
  compareSshPublicKeys,
  fingerprintSshPublicKey,
  generateSshKeyPair,
  normalizeSshPublicKey,
} from "./ssh/keys.js";
export { createGitSshServer, parseGitSshCommand } from "./ssh/server.js";
export {
  listRepositoryTree,
  readRepositoryBlob,
  readRepositoryCommit,
  readRepositoryCompare,
} from "./core/inspect.js";
export {
  abortRepositoryOperation,
  commitRepository,
  continueRepositoryOperation,
  discardRepositoryPaths,
  readRepositoryStagedFile,
  readRepositoryUnstagedFile,
  readRepositoryWorkingTree,
  stageRepositoryPaths,
  unstageRepositoryPaths,
} from "./core/working_tree.js";
export {
  buildGitEnv,
  cloneRepository,
  createInitialCommit,
  ensureManagedExcludeFile,
  initRepository,
  repositoryExists,
  runGit,
  runGitBuffer,
} from "./core/run_git.js";
export { GitHostError, isGitHostError } from "./errors.js";
export { assertAbsoluteRepositoryPath, normalizeRepositoryRelativePath, resolveRepositoryPath } from "./utils/paths.js";

export type { GitHostErrorCode } from "./errors.js";
export type { GenerateGitSshKeyPairOptions, GitSshKeyAlgorithm, GitSshKeyPair } from "./ssh/keys.js";
export type {
  BuildGitEnvOptions,
  CheckoutBranchInput,
  CheckoutRefInput,
  CommitInput,
  ContinueOperationInput,
  CreateBranchInput,
  CreateGitApiHandlerOptions,
  CreateGitHostOptions,
  DeleteBranchInput,
  DiscardPathsInput,
  DiffOptions,
  EnsureRepositoryOptions,
  FetchOptions,
  GitApiAuthorizationResult,
  GitApiResource,
  CreateGitHttpHandlerOptions,
  CreateGitSshServerOptions,
  GitActor,
  GitBlob,
  GitBlobEncoding,
  GitFileContent,
  GitFileContentSource,
  GitHttpAuthenticationResult,
  GitHttpAuditEvent,
  GitHttpAuditOutcome,
  GitHttpAuthorizationResult,
  GitHttpResolvedRepository,
  GitHttpService,
  GitBranchSummary,
  GitCommandBufferResult,
  GitCommandResult,
  GitCommitDetail,
  GitCommitSummary,
  GitCompareSummary,
  GitDiffFile,
  GitHost,
  GitHostGenericLogMethod,
  GitHostLogEvent,
  GitHostLogMethod,
  GitHostLogger,
  GitOperationKind,
  GitOperationState,
  GitRemoteCredentials,
  GitRemoteSummary,
  GitRemoteTransportOptions,
  GitRepositoryHandle,
  GitRepositoryStatus,
  GitRepositorySummary,
  GitSshAuditEvent,
  GitSshAuditOutcome,
  GitSshAuthenticationResult,
  GitSshAuthorizationResult,
  GitSshResolvedRepository,
  GitSshService,
  GitStatusEntry,
  GitTreeEntry,
  GitWorkingTree,
  GitWorkingTreeEntry,
  ListCommitsOptions,
  ListTreeOptions,
  MaybePromise,
  NormalizedGitHostLogger,
  PullOptions,
  PushOptions,
  ReadBlobOptions,
  ReadWorkingTreeFileOptions,
  ReadSummaryOptions,
  ResolveRepositoryPathOptions,
  StagePathsInput,
  UnstagePathsInput,
} from "./types.js";
